trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  resourceGroupName: 'arash-shared-rg' # Resource group name. Change it to your own resource group name

steps:
- task: AzureCLI@2
  displayName: 'Bicep Deployer function'
  inputs:
    azureSubscription: 'test-automatic' # Azure Resource Manager service connection. Change it to your own service connection
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $deploymentName="pipeline-run-$(Build.BuildNumber)"
      az deployment group create `
        --resource-group $(resourceGroupName) `
        --template-file ./infra/storageAccount.bicep `
        --name $deploymentName `
        --parameters tags="{'PipelineRunID':'$(Build.BuildNumber)'}"
      
      # Add build tag to Azure Pipeline run
      echo "##vso[build.addbuildtag]$deploymentName"