trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  resourceGroupName: 'arash-shared-rg' # Resource group name. Change it to your own resource group name

steps:
- task: AzureCLI@2
  displayName: 'Bicep Deployer function'
  inputs:
    azureSubscription: 'test-automatic'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $deploymentName="pipeline-run-$(Build.BuildId)"
      az deployment group create `
        --resource-group $(resourceGroupName) `
        --template-file ./infra/storageAccount.bicep `
        --name $deploymentName `
        --parameters tags="{'PipelineRunID':'$(Build.BuildId)'}"
      
      # Add build tag to Azure Pipeline run
      echo "##vso[build.addbuildtag]deploymentName:$deploymentName"